sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U setuptools wheel
  - pip install tox tox-travis tox-venv
  - python setup.py bdist_wheel

script:
  - tox --installpkg ./dist/django_registration_invite-*.whl

matrix:
  include:
    - python: 3.6
      env: TOXENV=isort
    - python: 3.6
      env: TOXENV=warnings
